### ISSUE TITLE
Setup Queries

### ISSUE THREAD

**Issue by shobhitpuri** [VladKorzun/cocoapods-githooks#1]
1. Is it required for every developer working on the project to run `$ gem install cocoapods-githooks
` step?

2. `plugin 'cocoapods-githooks'` can this be made for debug builds only? If not, would it increase the size of the app in release builds?

3. Should the folder be named `.git-hook` or `git-hooks`? Adding `.` makes it a hidden folder or system folder right? Is that intended?

**Comment by VladKorzun** [comment]
Hi @shobhitpuri 
Thanks for your interest in cocoapods-githooks plugin.
1. Yes, in order to use this plugin it should be installed by all team members. We use 
`plugin 'cocoapods-githooks'`
line in Podfile to make sure everybody has it.
2. No. It will not increase the app size in any way. 
3. Yes, it should be named `.git-hooks` and it's hidden the same way as `.git` directory does.
